[package]
name = "drempelbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mfrc522 = "0.6.0"
linux-embedded-hal = "0.3.2"
embedded-hal = "0.2.7"
itertools = "0.11.0"
bitflags = "2.4.0"
